/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Contact: typeof import('./src/pages/Contact.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HelloWorld2: typeof import('./src/components/HelloWorld2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
